// SPDX-FileCopyrightText: Copyright Orangebot, Inc. and Medplum contributors
// SPDX-License-Identifier: Apache-2.0
import { evalFhirPathTyped, toTypedValue } from '@medplum/core';
import type { Organization, Patient, Resource } from '@medplum/fhirtypes';

/**
 * Merge-field rendering. Templates carry `{{root.fhir.path}}` placeholders
 * where root is one of `patient`, `resource` (the trigger context resource),
 * or `clinic` (the sending Organization). The rest is a FHIRPath expression
 * evaluated against that root. Unresolvable fields render as ''.
 */

export interface RenderContext {
  patient: Patient;
  /** The trigger-context resource (Appointment, Encounter, ...), if any. */
  resource?: Resource;
  clinic?: Organization;
  /**
   * Per-recipient unsubscribe link, substituted for the reserved
   * `{{unsubscribe}}` field the locked footer always contains. Generated by the
   * executor — never configured by an operator.
   */
  unsubscribeUrl?: string;
}

/**
 * Reserved merge field (no FHIRPath root) resolved from the render context
 * rather than a resource.
 */
export const UNSUBSCRIBE_FIELD = 'unsubscribe';

const MERGE_FIELD_REGEX = /\{\{\s*([^}]+?)\s*\}\}/g;

/**
 * Extracts the distinct merge fields used in a template body/subject.
 * @param content - HTML or subject text.
 * @returns Distinct field expressions (e.g. `patient.name.given.first()`).
 */
export function extractMergeFields(content: string): string[] {
  const fields = new Set<string>();
  for (const match of content.matchAll(MERGE_FIELD_REGEX)) {
    fields.add(match[1]);
  }
  return [...fields];
}

/** Roots allowed in merge fields, in priority order. */
export const MERGE_ROOTS = ['patient', 'resource', 'clinic'] as const;
export type MergeRoot = (typeof MERGE_ROOTS)[number];

/**
 * Splits a merge field into root + FHIRPath, e.g.
 * `patient.name.given.first()` → { root: 'patient', path: 'name.given.first()' }.
 * @param field - The raw field expression.
 * @returns The parsed field, or undefined for an unknown root.
 */
export function parseMergeField(field: string): { root: MergeRoot; path: string } | undefined {
  const dot = field.indexOf('.');
  const root = (dot === -1 ? field : field.slice(0, dot)) as MergeRoot;
  if (!MERGE_ROOTS.includes(root)) {
    return undefined;
  }
  return { root, path: dot === -1 ? '' : field.slice(dot + 1) };
}

/**
 * Evaluates a single merge field against the render context.
 * @param field - The raw field expression.
 * @param context - Patient / trigger resource / clinic.
 * @returns The string value ('' when unresolvable).
 */
export function evaluateMergeField(field: string, context: RenderContext): string {
  if (field === UNSUBSCRIBE_FIELD) {
    return context.unsubscribeUrl ?? '';
  }
  const parsed = parseMergeField(field);
  if (!parsed) {
    return '';
  }
  const roots: Record<MergeRoot, Resource | undefined> = {
    patient: context.patient,
    resource: context.resource,
    clinic: context.clinic,
  };
  const rootResource = roots[parsed.root];
  if (!rootResource) {
    return '';
  }
  if (!parsed.path) {
    return '';
  }
  try {
    const results = evalFhirPathTyped(parsed.path, [toTypedValue(rootResource)]);
    const value = results[0]?.value;
    if (value === undefined || value === null) {
      return '';
    }
    return typeof value === 'object' ? JSON.stringify(value) : String(value);
  } catch {
    return '';
  }
}

/**
 * Renders all merge fields in a template string.
 * @param content - HTML or subject text with `{{...}}` placeholders.
 * @param context - Patient / trigger resource / clinic.
 * @returns The rendered string.
 */
export function renderMergeFields(content: string, context: RenderContext): string {
  return content.replace(MERGE_FIELD_REGEX, (_, field: string) => evaluateMergeField(field.trim(), context));
}
