/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type OpeningHours = {
  _type: "openingHours";
  days?: string;
  hours?: string;
};

export type Faq = {
  _type: "faq";
  question?: string;
  answer?: string;
};

export type CtaLink = {
  _type: "ctaLink";
  label?: string;
  href?: string;
};

export type Announcement = {
  _type: "announcement";
  text?: string;
  link?: string;
};

export type Stat = {
  _type: "stat";
  value?: string;
  label?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "contentImage";
  _key: string;
}>;

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  website?: string;
  orderRank?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Publication = {
  _id: string;
  _type: "publication";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publicationType?: "research" | "report" | "guideline" | "resource" | "newsletter";
  abstract?: string;
  authors?: Array<{
    _key: string;
  } & AuthorReference>;
  externalAuthors?: Array<string>;
  publishedAt?: string;
  journal?: string;
  doi?: string;
  externalUrl?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  body?: BlockContent;
  seo?: Seo;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  author?: AuthorReference;
  categories?: Array<{
    _key: string;
  } & CategoryReference>;
  publishedAt?: string;
  body?: BlockContent;
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: BlockContent;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  icon?: "stethoscope" | "heart" | "heartPulse" | "baby" | "bone" | "brain" | "eye" | "sparkles" | "droplet" | "activity" | "clipboardList" | "users" | "pill" | "scan" | "microscope";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
  faqs?: Array<{
    _key: string;
  } & Faq>;
  orderRank?: number;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  phone?: string;
  email?: string;
  address?: string;
  openingHours?: Array<{
    _key: string;
  } & OpeningHours>;
  socialLinks?: Array<{
    platform?: "facebook" | "instagram" | "linkedin" | "x" | "youtube";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  navigation?: Array<{
    _key: string;
  } & CtaLink>;
  footerNavigation?: Array<{
    _key: string;
  } & CtaLink>;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    heading?: string;
    intro?: string;
    callToAction?: CtaLink;
    backgroundImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    images?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }>;
    announcements?: Array<{
      _key: string;
    } & Announcement>;
  };
  servicesSection?: {
    eyebrow?: string;
    heading?: string;
    intro?: string;
  };
  aboutSection?: {
    eyebrow?: string;
    heading?: string;
    body?: BlockContent;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    featuredStat?: Stat;
    stats?: Array<{
      _key: string;
    } & Stat>;
  };
  partnersSection?: {
    heading?: string;
    intro?: string;
  };
  contactSection?: {
    eyebrow?: string;
    heading?: string;
    intro?: string;
  };
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = OpeningHours | Faq | CtaLink | Announcement | Stat | SanityImageAssetReference | Seo | BlockContent | Partner | SanityImageCrop | SanityImageHotspot | Category | Slug | AuthorReference | SanityFileAssetReference | CategoryReference | Publication | Post | Author | Service | SiteSettings | HomePage | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    title,    description,    logo{  asset,  hotspot,  crop,  alt},    phone,    email,    address,    openingHours[]{_key, days, hours},    socialLinks[]{_key, platform, url},    navigation[]{_key, label, href},    footerNavigation[]{_key, label, href}  }
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  logo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: null;
  } | null;
  phone: string | null;
  email: string | null;
  address: string | null;
  openingHours: Array<{
    _key: string;
    days: string | null;
    hours: string | null;
  }> | null;
  socialLinks: Array<{
    _key: string;
    platform: "facebook" | "instagram" | "linkedin" | "x" | "youtube" | null;
    url: string | null;
  }> | null;
  navigation: Array<{
    _key: string;
    label: string | null;
    href: string | null;
  }> | null;
  footerNavigation: Array<{
    _key: string;
    label: string | null;
    href: string | null;
  }> | null;
} | null;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{    hero{      heading,      intro,      callToAction{label, href},      backgroundImage{  asset,  hotspot,  crop,  alt},      images[]{_key,   asset,  hotspot,  crop,  alt},      announcements[]{_key, text, link}    },    servicesSection{eyebrow, heading, intro},    aboutSection{      eyebrow,      heading,      body,      image{  asset,  hotspot,  crop,  alt},      featuredStat{value, label},      stats[]{_key, value, label}    },    partnersSection{heading, intro},    contactSection{eyebrow, heading, intro},    seo{title, description, image{  asset,  hotspot,  crop,  alt}}  }
export type HOME_PAGE_QUERY_RESULT = {
  hero: {
    heading: string | null;
    intro: string | null;
    callToAction: {
      label: string | null;
      href: string | null;
    } | null;
    backgroundImage: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: null;
    } | null;
    images: Array<{
      _key: string;
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
    }> | null;
    announcements: Array<{
      _key: string;
      text: string | null;
      link: string | null;
    }> | null;
  } | null;
  servicesSection: {
    eyebrow: string | null;
    heading: string | null;
    intro: string | null;
  } | null;
  aboutSection: {
    eyebrow: string | null;
    heading: string | null;
    body: BlockContent | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
    } | null;
    featuredStat: {
      value: string | null;
      label: string | null;
    } | null;
    stats: Array<{
      _key: string;
      value: string | null;
      label: string | null;
    }> | null;
  } | null;
  partnersSection: {
    heading: string | null;
    intro: string | null;
  } | null;
  contactSection: {
    eyebrow: string | null;
    heading: string | null;
    intro: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: null;
    } | null;
  } | null;
} | null;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(orderRank asc, title asc){    _id,    title,    "slug": slug.current,    summary,    icon,    image{  asset,  hotspot,  crop,  alt}  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  icon: "activity" | "baby" | "bone" | "brain" | "clipboardList" | "droplet" | "eye" | "heart" | "heartPulse" | "microscope" | "pill" | "scan" | "sparkles" | "stethoscope" | "users" | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
}>;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: SERVICES_PAGE_QUERY
// Query: *[_type == "service"] | order(orderRank asc, title asc){    _id,    title,    "slug": slug.current,    summary,    icon,    image{  asset,  hotspot,  crop,  alt},    body,    faqs[]{_key, question, answer}  }
export type SERVICES_PAGE_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  icon: "activity" | "baby" | "bone" | "brain" | "clipboardList" | "droplet" | "eye" | "heart" | "heartPulse" | "microscope" | "pill" | "scan" | "sparkles" | "stethoscope" | "users" | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  body: BlockContent | null;
  faqs: Array<{
    _key: string;
    question: string | null;
    answer: string | null;
  }> | null;
}>;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: SERVICE_QUERY
// Query: *[_type == "service" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    summary,    icon,    image{  asset,  hotspot,  crop,  alt},    body,    seo{title, description, image{  asset,  hotspot,  crop,  alt}}  }
export type SERVICE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  icon: "activity" | "baby" | "bone" | "brain" | "clipboardList" | "droplet" | "eye" | "heart" | "heartPulse" | "microscope" | "pill" | "scan" | "sparkles" | "stethoscope" | "users" | null;
  image: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  body: BlockContent | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: null;
    } | null;
  } | null;
} | null;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: PARTNERS_QUERY
// Query: *[_type == "partner"] | order(orderRank asc, name asc){    _id,    name,    logo{  asset,  hotspot,  crop,  alt},    website  }
export type PARTNERS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  logo: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  website: string | null;
}>;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){      _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage{  asset,  hotspot,  crop,  alt},  author->{_id, name, "slug": slug.current, role, image{  asset,  hotspot,  crop,  alt}},  categories[]->{_id, title, "slug": slug.current}  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  mainImage: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage{  asset,  hotspot,  crop,  alt},  author->{_id, name, "slug": slug.current, role, image{  asset,  hotspot,  crop,  alt}},  categories[]->{_id, title, "slug": slug.current},    body,    seo{title, description, image{  asset,  hotspot,  crop,  alt}}  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  mainImage: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  author: {
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  body: BlockContent | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: null;
    } | null;
  } | null;
} | null;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{"slug": slug.current}
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: PUBLICATIONS_QUERY
// Query: *[_type == "publication" && defined(slug.current)] | order(publishedAt desc){      _id,  title,  "slug": slug.current,  publicationType,  abstract,  publishedAt,  journal,  doi,  externalUrl,  "fileUrl": file.asset->url,  coverImage{  asset,  hotspot,  crop,  alt},  authors[]->{_id, name, "slug": slug.current, role},  externalAuthors,  categories[]->{_id, title, "slug": slug.current}  }
export type PUBLICATIONS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  publicationType: "guideline" | "newsletter" | "report" | "research" | "resource" | null;
  abstract: string | null;
  publishedAt: string | null;
  journal: string | null;
  doi: string | null;
  externalUrl: string | null;
  fileUrl: string | null;
  coverImage: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  authors: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
  }> | null;
  externalAuthors: Array<string> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: PUBLICATION_QUERY
// Query: *[_type == "publication" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  publicationType,  abstract,  publishedAt,  journal,  doi,  externalUrl,  "fileUrl": file.asset->url,  coverImage{  asset,  hotspot,  crop,  alt},  authors[]->{_id, name, "slug": slug.current, role},  externalAuthors,  categories[]->{_id, title, "slug": slug.current},    body,    seo{title, description, image{  asset,  hotspot,  crop,  alt}}  }
export type PUBLICATION_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  publicationType: "guideline" | "newsletter" | "report" | "research" | "resource" | null;
  abstract: string | null;
  publishedAt: string | null;
  journal: string | null;
  doi: string | null;
  externalUrl: string | null;
  fileUrl: string | null;
  coverImage: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
  } | null;
  authors: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    role: string | null;
  }> | null;
  externalAuthors: Array<string> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  body: BlockContent | null;
  seo: {
    title: string | null;
    description: string | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: null;
    } | null;
  } | null;
} | null;

// Source: ../../premierhealthrecords/examples/website/sanity/lib/queries.ts
// Variable: PUBLICATION_SLUGS_QUERY
// Query: *[_type == "publication" && defined(slug.current)]{"slug": slug.current}
export type PUBLICATION_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    "\n  *[_type == \"siteSettings\"][0]{\n    title,\n    description,\n    logo{\n  asset,\n  hotspot,\n  crop,\n  alt\n},\n    phone,\n    email,\n    address,\n    openingHours[]{_key, days, hours},\n    socialLinks[]{_key, platform, url},\n    navigation[]{_key, label, href},\n    footerNavigation[]{_key, label, href}\n  }\n": SITE_SETTINGS_QUERY_RESULT;
    "\n  *[_type == \"homePage\"][0]{\n    hero{\n      heading,\n      intro,\n      callToAction{label, href},\n      backgroundImage{\n  asset,\n  hotspot,\n  crop,\n  alt\n},\n      images[]{_key, \n  asset,\n  hotspot,\n  crop,\n  alt\n},\n      announcements[]{_key, text, link}\n    },\n    servicesSection{eyebrow, heading, intro},\n    aboutSection{\n      eyebrow,\n      heading,\n      body,\n      image{\n  asset,\n  hotspot,\n  crop,\n  alt\n},\n      featuredStat{value, label},\n      stats[]{_key, value, label}\n    },\n    partnersSection{heading, intro},\n    contactSection{eyebrow, heading, intro},\n    seo{title, description, image{\n  asset,\n  hotspot,\n  crop,\n  alt\n}}\n  }\n": HOME_PAGE_QUERY_RESULT;
    "\n  *[_type == \"service\"] | order(orderRank asc, title asc){\n    _id,\n    title,\n    \"slug\": slug.current,\n    summary,\n    icon,\n    image{\n  asset,\n  hotspot,\n  crop,\n  alt\n}\n  }\n": SERVICES_QUERY_RESULT;
    "\n  *[_type == \"service\"] | order(orderRank asc, title asc){\n    _id,\n    title,\n    \"slug\": slug.current,\n    summary,\n    icon,\n    image{\n  asset,\n  hotspot,\n  crop,\n  alt\n},\n    body,\n    faqs[]{_key, question, answer}\n  }\n": SERVICES_PAGE_QUERY_RESULT;
    "\n  *[_type == \"service\" && slug.current == $slug][0]{\n    _id,\n    title,\n    \"slug\": slug.current,\n    summary,\n    icon,\n    image{\n  asset,\n  hotspot,\n  crop,\n  alt\n},\n    body,\n    seo{title, description, image{\n  asset,\n  hotspot,\n  crop,\n  alt\n}}\n  }\n": SERVICE_QUERY_RESULT;
    "\n  *[_type == \"partner\"] | order(orderRank asc, name asc){\n    _id,\n    name,\n    logo{\n  asset,\n  hotspot,\n  crop,\n  alt\n},\n    website\n  }\n": PARTNERS_QUERY_RESULT;
    "\n  *[_type == \"post\" && defined(slug.current)] | order(publishedAt desc){\n    \n  _id,\n  title,\n  \"slug\": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage{\n  asset,\n  hotspot,\n  crop,\n  alt\n},\n  author->{_id, name, \"slug\": slug.current, role, image{\n  asset,\n  hotspot,\n  crop,\n  alt\n}},\n  categories[]->{_id, title, \"slug\": slug.current}\n\n  }\n": POSTS_QUERY_RESULT;
    "\n  *[_type == \"post\" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  \"slug\": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage{\n  asset,\n  hotspot,\n  crop,\n  alt\n},\n  author->{_id, name, \"slug\": slug.current, role, image{\n  asset,\n  hotspot,\n  crop,\n  alt\n}},\n  categories[]->{_id, title, \"slug\": slug.current}\n,\n    body,\n    seo{title, description, image{\n  asset,\n  hotspot,\n  crop,\n  alt\n}}\n  }\n": POST_QUERY_RESULT;
    "\n  *[_type == \"post\" && defined(slug.current)]{\"slug\": slug.current}\n": POST_SLUGS_QUERY_RESULT;
    "\n  *[_type == \"publication\" && defined(slug.current)] | order(publishedAt desc){\n    \n  _id,\n  title,\n  \"slug\": slug.current,\n  publicationType,\n  abstract,\n  publishedAt,\n  journal,\n  doi,\n  externalUrl,\n  \"fileUrl\": file.asset->url,\n  coverImage{\n  asset,\n  hotspot,\n  crop,\n  alt\n},\n  authors[]->{_id, name, \"slug\": slug.current, role},\n  externalAuthors,\n  categories[]->{_id, title, \"slug\": slug.current}\n\n  }\n": PUBLICATIONS_QUERY_RESULT;
    "\n  *[_type == \"publication\" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  \"slug\": slug.current,\n  publicationType,\n  abstract,\n  publishedAt,\n  journal,\n  doi,\n  externalUrl,\n  \"fileUrl\": file.asset->url,\n  coverImage{\n  asset,\n  hotspot,\n  crop,\n  alt\n},\n  authors[]->{_id, name, \"slug\": slug.current, role},\n  externalAuthors,\n  categories[]->{_id, title, \"slug\": slug.current}\n,\n    body,\n    seo{title, description, image{\n  asset,\n  hotspot,\n  crop,\n  alt\n}}\n  }\n": PUBLICATION_QUERY_RESULT;
    "\n  *[_type == \"publication\" && defined(slug.current)]{\"slug\": slug.current}\n": PUBLICATION_SLUGS_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}

